# Generated by Django 3.1.3 on 2020-11-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_pupa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupa',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
