# Generated by Django 3.1.3 on 2020-11-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20201124_1528'),
    ]

    operations = [

    ]
