# Generated by Django 3.1.3 on 2020-11-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20201124_1643'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
