# Generated by Django 3.1.3 on 2020-12-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='keycloack_id',
            new_name='keycloak_id',
        ),
    ]
